const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let deferredInstall=null,peer=null,conn=null,localStream=null;
function openGame(id){location.href=`player.html?game=${encodeURIComponent(id)}`}
function fullscreen(){document.documentElement.requestFullscreen?.().catch(()=>{});screen.orientation?.lock?.('landscape').catch?.(()=>{})}
function randomCode(){return String(Math.floor(1000+Math.random()*9000))}
async function voice(){try{return await navigator.mediaDevices.getUserMedia({audio:true,video:false})}catch(e){return null}}
async function host(){const code=randomCode();$('#roomCode').textContent=code;$('#netStatus').textContent='建立房間中…';localStream=await voice();peer=new Peer('cps-'+code+'-host');peer.on('open',()=>$('#netStatus').textContent='房間已建立，等待朋友加入');peer.on('connection',c=>{conn=c;$('#netStatus').textContent='已連線'});peer.on('call',call=>{call.answer(localStream||undefined);call.on('stream',s=>{const a=new Audio();a.autoplay=true;a.srcObject=s})});peer.on('error',()=>$('#netStatus').textContent='房號衝突，請重新建立')}
async function join(){const code=$('#joinCode').value.replace(/\D/g,'').slice(0,4);if(code.length!==4){$('#netStatus').textContent='請輸入 4 碼邀請碼';return}$('#roomCode').textContent=code;localStream=await voice();peer=new Peer();peer.on('open',()=>{conn=peer.connect('cps-'+code+'-host');conn.on('open',()=>$('#netStatus').textContent='已連線');if(localStream){const call=peer.call('cps-'+code+'-host',localStream);call.on('stream',s=>{const a=new Audio();a.autoplay=true;a.srcObject=s})}});peer.on('error',()=>$('#netStatus').textContent='找不到房間或連線失敗')}
function pwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBanner').classList.remove('hidden')});const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);if(ios&&!navigator.standalone&&!localStorage.getItem('installDismiss')){$('#installBanner span').textContent='iPhone/iPad：分享 → 加入主畫面';$('#installBanner').classList.remove('hidden')}$('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$('#installBanner').classList.add('hidden')}else if(ios)alert('Safari 的「分享」→「加入主畫面」即可安裝。')};$('#installClose').onclick=()=>{$('#installBanner').classList.add('hidden');localStorage.setItem('installDismiss','1')}}
document.addEventListener('DOMContentLoaded',()=>{$$('.game-card').forEach(b=>b.onclick=()=>openGame(b.dataset.game));$('#fullscreenHome').onclick=fullscreen;$('#multiOpen').onclick=()=>$('#multiModal').classList.remove('hidden');$('#multiClose').onclick=()=>$('#multiModal').classList.add('hidden');$('#hostRoom').onclick=host;$('#joinRoom').onclick=join;pwa()});
