const VERSION='v1.2';
const games=[
{id:'knights',name:'圓桌武士',core:'fbneo',file:'../roms/knightsj.zip',parent:'../roms/knights.zip',emoji:'⚔️',gameId:1201,system:'ARCADE・FBNeo'},
{id:'sf3',name:'快打旋風3',core:'nes',file:'roms/快打旋風3.nes',emoji:'🥊',gameId:1202,system:'NES'}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let currentGame=null,deferredPrompt=null,soundOn=true,voiceOn=true,turboOn=false,widthIndex=0,peer=null,conn=null,localStream=null,mediaCall=null,roomCode=null,isHost=false,dpadPointer=null;let activeDirs=new Set(),turboTimers={};
const widths=[100,95,90,85,80,75,70,65,60],saved=JSON.parse(localStorage.getItem('memeArcadeSettings')||'{}');
function save(){localStorage.setItem('memeArcadeSettings',JSON.stringify({soundOn,voiceOn,turboOn,widthIndex,leftX:$('#leftX').value,leftY:$('#leftY').value,rightX:$('#rightX').value,rightY:$('#rightY').value,scale:$('#controlScale').value}))}
function renderGames(){$('#gameGrid').innerHTML=games.map((g,i)=>`<button class="gameCard" data-game="${g.id}"><span class="num">0${i+1}</span><div class="emoji">${g.emoji}</div><b>${g.name}</b><span>${g.system}・點一下開始</span><span class="badge">內建遊戲</span></button>`).join('');$$('[data-game]').forEach(b=>b.onclick=()=>launchGame(games.find(g=>g.id===b.dataset.game)))}
function launchGame(g){currentGame=g;$('#launcher').classList.remove('show');$('#playScreen').classList.add('show');$('#loading').classList.remove('hidden');$('#loadingText').textContent=`正在載入 ${g.name}`;try{window.EJS_emulator?.terminate?.()}catch(e){}$('#game').innerHTML='';window.EJS_player='#game';window.EJS_core=g.core;window.EJS_gameUrl=new URL(g.file,document.baseURI).href;window.EJS_gameName=g.name;window.EJS_pathtodata='https://cdn.emulatorjs.org/stable/data/';window.EJS_startOnLoaded=true;window.EJS_color='#111';window.EJS_backgroundColor='#000';window.EJS_volume=soundOn?1:0;window.EJS_VirtualGamepad=false;window.EJS_gameID=g.gameId;if(g.parent)window.EJS_gameParentUrl=new URL(g.parent,document.baseURI).href;else try{delete window.EJS_gameParentUrl}catch(e){};const old=$('#ejsLoader');if(old)old.remove();const s=document.createElement('script');s.id='ejsLoader';s.src='https://cdn.emulatorjs.org/stable/data/loader.js';s.onload=()=>setTimeout(()=>$('#loading').classList.add('hidden'),1100);s.onerror=()=>$('#loadingText').textContent='模擬器載入失敗';document.body.appendChild(s);screen.orientation?.lock?.('landscape').catch?.(()=>{})}
function goHome(){releaseAll();$('#playScreen').classList.remove('show');$('#launcher').classList.add('show');$('#quickMenu').classList.remove('open')}
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){}screen.orientation?.lock?.('landscape').catch?.(()=>{})}
function emitKey(key,down,remote=false){const map={ArrowUp:38,ArrowDown:40,ArrowLeft:37,ArrowRight:39,z:90,x:88,Enter:13,Shift:16,i:73,k:75,j:74,l:76,n:78,m:77};const ev=new KeyboardEvent(down?'keydown':'keyup',{key,code:key.startsWith('Arrow')?key:key==='Enter'?'Enter':key==='Shift'?'ShiftLeft':'Key'+key.toUpperCase(),keyCode:map[key]||0,which:map[key]||0,bubbles:true,cancelable:true});window.dispatchEvent(ev);document.dispatchEvent(ev);if(conn?.open&&!remote)conn.send({t:'key',key,down})}
const remoteMap=k=>({ArrowUp:'i',ArrowDown:'k',ArrowLeft:'j',ArrowRight:'l',z:'n',x:'m',Enter:'Enter',Shift:'Shift'}[k]||k),haptic=()=>navigator.vibrate?.(8);
function dirVisual(k,on){const m={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};$('.dpadArm.'+m[k])?.classList.toggle('pressed',on)}
function setDirs(next){const n=new Set(next);for(const d of activeDirs)if(!n.has(d)){emitKey(d,false);dirVisual(d,false)}for(const d of n)if(!activeDirs.has(d)){emitKey(d,true);dirVisual(d,true);haptic()}activeDirs=n}
function dpadAt(x,y){const r=$('#dpad').getBoundingClientRect(),dx=(x-r.left-r.width/2)/(r.width/2),dy=(y-r.top-r.height/2)/(r.height/2);if(Math.hypot(dx,dy)<.13)return[];const o=[];if(dy<-.25)o.push('ArrowUp');if(dy>.25)o.push('ArrowDown');if(dx<-.25)o.push('ArrowLeft');if(dx>.25)o.push('ArrowRight');if(!o.length)o.push(Math.abs(dx)>Math.abs(dy)?(dx>0?'ArrowRight':'ArrowLeft'):(dy>0?'ArrowDown':'ArrowUp'));return o}
function bindDpad(){const z=$('#dpadZone');z.onpointerdown=e=>{dpadPointer=e.pointerId;z.setPointerCapture?.(e.pointerId);setDirs(dpadAt(e.clientX,e.clientY));e.preventDefault()};z.onpointermove=e=>{if(e.pointerId===dpadPointer)setDirs(dpadAt(e.clientX,e.clientY))};['pointerup','pointercancel','lostpointercapture'].forEach(t=>z.addEventListener(t,e=>{if(dpadPointer===null||e.pointerId===dpadPointer){setDirs([]);dpadPointer=null}}))}
function press(el,down){const key=el.dataset.key;if(!key)return;el.classList.toggle('pressed',down);if(down){haptic();emitKey(key,true);if(turboOn&&(key==='z'||key==='x')){clearInterval(turboTimers[key]);turboTimers[key]=setInterval(()=>{emitKey(key,false);setTimeout(()=>emitKey(key,true),24)},90)}}else{clearInterval(turboTimers[key]);delete turboTimers[key];emitKey(key,false)}}
function bindButtons(){$$('.actionZone [data-key]').forEach(el=>{el.onpointerdown=e=>{el.setPointerCapture?.(e.pointerId);press(el,true);e.preventDefault()};['pointerup','pointercancel','lostpointercapture'].forEach(t=>el.addEventListener(t,()=>press(el,false)))})}
function releaseAll(){setDirs([]);$$('.actionZone [data-key]').forEach(e=>press(e,false))}
function setWidth(){const w=widths[widthIndex];document.documentElement.style.setProperty('--stageScale',w/100);$('#widthLabel').textContent=w+'%';save()}
function applyControls(){const v={lx:$('#leftX').value,ly:$('#leftY').value,rx:$('#rightX').value,ry:$('#rightY').value,s:$('#controlScale').value};document.documentElement.style.setProperty('--leftX',v.lx+'vw');document.documentElement.style.setProperty('--leftY',v.ly+'vh');document.documentElement.style.setProperty('--rightX',v.rx+'vw');document.documentElement.style.setProperty('--rightY',v.ry+'vh');document.documentElement.style.setProperty('--controlScale',v.s/100);$('#leftXOut').textContent=v.lx;$('#leftYOut').textContent=v.ly;$('#rightXOut').textContent=v.rx;$('#rightYOut').textContent=v.ry;$('#scaleOut').textContent=v.s+'%';save()}
const openModal=id=>$(id).classList.add('show'),closeModals=()=>$$('.modal').forEach(m=>m.classList.remove('show')),genCode=()=>String(Math.floor(1000+Math.random()*9000));
function status(s,ok=false){$('#roomStatus').textContent='● '+s;$('#roomStatus').classList.toggle('connected',ok)}
async function mic(){if(localStream)return localStream;localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});localStream.getAudioTracks().forEach(t=>t.enabled=voiceOn);return localStream}
function bindConn(c){c.on('open',async()=>{status('已連線',true);if(voiceOn&&!isHost)try{const st=await mic();mediaCall=peer.call('meme-'+roomCode,st);mediaCall.on('stream',rs=>$('#remoteAudio').srcObject=rs)}catch(e){}});c.on('data',d=>{if(d?.t==='key')emitKey(isHost?remoteMap(d.key):d.key,d.down,true)});c.on('close',()=>status('對方已離線'))}
function peerEvents(){peer.on('connection',c=>{conn=c;bindConn(c)});peer.on('call',async call=>{try{const st=await mic();call.answer(st);call.on('stream',rs=>$('#remoteAudio').srcObject=rs)}catch(e){call.answer()}});peer.on('error',()=>status('連線失敗，請重試'))}
function createRoom(){roomCode=genCode();isHost=true;$('#roomCode').textContent=roomCode;peer?.destroy();peer=new Peer('meme-'+roomCode);peerEvents();peer.on('open',()=>status('等待朋友加入 '+roomCode))}
function joinRoom(){const c=$('#joinCode').value.replace(/\D/g,'').slice(0,4);if(c.length!==4)return status('請輸入 4 碼');roomCode=c;isHost=false;peer?.destroy();peer=new Peer();peerEvents();peer.on('open',()=>{conn=peer.connect('meme-'+c,{reliable:true});bindConn(conn)})}
function install(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else{$('#installInstructions').innerHTML=/iphone|ipad|ipod/i.test(navigator.userAgent)?'<b>iPhone / iPad</b><br>Safari → 分享 → 加入主畫面。':'<b>Android</b><br>瀏覽器選單 → 安裝應用程式／加入主畫面。';openModal('#installModal')}};if(!matchMedia('(display-mode: standalone)').matches&&!navigator.standalone)setTimeout(()=>$('#installBtn').classList.remove('hidden'),600)}
function bindUI(){$('#quickToggle').onclick=()=>$('#quickMenu').classList.toggle('open');$('#fullscreenLauncherBtn').onclick=fullscreen;$('#openRoomBtn').onclick=()=>openModal('#roomModal');$$('#quickMenu [data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='sound'){soundOn=!soundOn;$('#soundIcon').textContent=soundOn?'🔊':'🔇';try{EJS_emulator?.setVolume?.(soundOn?1:0)}catch(e){}save()}if(a==='width'){widthIndex=(widthIndex+1)%widths.length;setWidth()}if(a==='voice'){voiceOn=!voiceOn;$('#voiceIcon').textContent=voiceOn?'🎙':'🔇';$('#voiceLabel').textContent='語音 '+(voiceOn?'ON':'OFF');localStream?.getAudioTracks().forEach(t=>t.enabled=voiceOn);save()}if(a==='controls')openModal('#controlsModal');if(a==='turbo'){turboOn=!turboOn;$('#turboLabel').textContent='連發 '+(turboOn?'ON':'OFF');save()}if(a==='fullscreen')fullscreen();if(a==='room')openModal('#roomModal');if(a==='home')goHome()});$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('[data-roomtab]').forEach(b=>b.onclick=()=>{$$('[data-roomtab]').forEach(x=>x.classList.toggle('active',x===b));$('#hostPane').classList.toggle('show',b.dataset.roomtab==='host');$('#joinPane').classList.toggle('show',b.dataset.roomtab==='join')});$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#joinCode').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4);$('#copyCode').onclick=()=>roomCode&&navigator.clipboard?.writeText(roomCode);['#leftX','#leftY','#rightX','#rightY','#controlScale'].forEach(id=>$(id).oninput=applyControls);$('#resetControls').onclick=()=>{$('#leftX').value=$('#leftY').value=$('#rightX').value=$('#rightY').value=0;$('#controlScale').value=100;applyControls()};document.addEventListener('visibilitychange',()=>document.hidden&&releaseAll())}
function restore(){soundOn=saved.soundOn??true;voiceOn=saved.voiceOn??true;turboOn=saved.turboOn??false;widthIndex=saved.widthIndex??0;$('#leftX').value=saved.leftX??0;$('#leftY').value=saved.leftY??0;$('#rightX').value=saved.rightX??0;$('#rightY').value=saved.rightY??0;$('#controlScale').value=saved.scale??100;$('#soundIcon').textContent=soundOn?'🔊':'🔇';$('#voiceIcon').textContent=voiceOn?'🎙':'🔇';$('#voiceLabel').textContent='語音 '+(voiceOn?'ON':'OFF');$('#turboLabel').textContent='連發 '+(turboOn?'ON':'OFF');setWidth();applyControls()}
renderGames();bindDpad();bindButtons();bindUI();restore();install();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});