const VERSION='v1.1';
const games=[
 {id:'ice',name:'敲冰塊',file:'roms/敲冰塊.nes',emoji:'🧊',gameId:1101},
 {id:'penguin',name:'南極企鵝',file:'roms/南極企鵝.nes',emoji:'🐧',gameId:1102},
 {id:'circus',name:'馬戲團',file:'roms/馬戲團.nes',emoji:'🎪',gameId:1103}
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentGame=null,deferredPrompt=null,soundOn=true,voiceOn=true,turboOn=false,widthIndex=0;
const widths=[100,95,90,85,80,75,70,65,60];
let peer=null,conn=null,localStream=null,mediaCall=null,roomCode=null,isHost=false;
let activeDirs=new Set(), dpadPointer=null, turboTimers={};
const saved=JSON.parse(localStorage.getItem('memeArcadeSettings')||'{}');
function saveSettings(){localStorage.setItem('memeArcadeSettings',JSON.stringify({soundOn,voiceOn,turboOn,widthIndex,leftX:$('#leftX').value,leftY:$('#leftY').value,rightX:$('#rightX').value,rightY:$('#rightY').value,scale:$('#controlScale').value}))}
function renderGames(){$('#gameGrid').innerHTML=games.map((g,i)=>`<button class="gameCard" data-game="${g.id}"><span class="num">0${i+1}</span><div class="emoji">${g.emoji}</div><b>${g.name}</b><span>NES・點一下開始</span><span class="badge">內建遊戲</span></button>`).join('');$$('[data-game]').forEach(b=>b.addEventListener('click',()=>launchGame(games.find(g=>g.id===b.dataset.game))));}
function launchGame(g){currentGame=g;$('#launcher').classList.remove('show');$('#playScreen').classList.add('show');$('#loading').classList.remove('hidden');$('#loadingText').textContent=`正在載入 ${g.name}`;if(window.EJS_emulator?.terminate)try{window.EJS_emulator.terminate()}catch(e){}$('#game').innerHTML='';window.EJS_player='#game';window.EJS_core='nes';window.EJS_gameUrl=g.file;window.EJS_gameName=g.name;window.EJS_pathtodata='https://cdn.emulatorjs.org/stable/data/';window.EJS_startOnLoaded=true;window.EJS_color='#111';window.EJS_backgroundColor='#000';window.EJS_volume=soundOn?1:0;window.EJS_VirtualGamepad=false;window.EJS_gameID=g.gameId;const old=document.getElementById('ejsLoader');if(old)old.remove();const s=document.createElement('script');s.id='ejsLoader';s.src='https://cdn.emulatorjs.org/stable/data/loader.js';s.onload=()=>setTimeout(()=>$('#loading').classList.add('hidden'),900);s.onerror=()=>{$('#loadingText').textContent='模擬器載入失敗，請檢查網路'};document.body.appendChild(s);requestFullscreenSoft();}
function goHome(){releaseAll();$('#playScreen').classList.remove('show');$('#launcher').classList.add('show');$('#quickMenu').classList.remove('open')}
function requestFullscreenSoft(){if(screen.orientation?.lock)screen.orientation.lock('landscape').catch(()=>{})}
async function toggleFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(e){}requestFullscreenSoft()}
function emitKey(key,down,remote=false){const codeMap={ArrowUp:38,ArrowDown:40,ArrowLeft:37,ArrowRight:39,z:90,x:88,Enter:13,Shift:16,i:73,k:75,j:74,l:76,n:78,m:77};const ev=new KeyboardEvent(down?'keydown':'keyup',{key,code:key.startsWith('Arrow')?key:(key==='Enter'?'Enter':key==='Shift'?'ShiftLeft':'Key'+key.toUpperCase()),keyCode:codeMap[key]||0,which:codeMap[key]||0,bubbles:true,cancelable:true});window.dispatchEvent(ev);document.dispatchEvent(ev);if(conn?.open&&!remote)conn.send({t:'key',key,down})}
function remoteMap(key){return{ArrowUp:'i',ArrowDown:'k',ArrowLeft:'j',ArrowRight:'l',z:'n',x:'m',Enter:'Enter',Shift:'Shift'}[key]||key}
function haptic(){if(navigator.vibrate)navigator.vibrate(8)}
function setDirs(next){const ns=new Set(next);for(const d of activeDirs)if(!ns.has(d)){emitKey(d,false);dirVisual(d,false)}for(const d of ns)if(!activeDirs.has(d)){emitKey(d,true);dirVisual(d,true);haptic()}activeDirs=ns}
function dirVisual(key,on){const m={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'};const el=$(`.dpadArm.${m[key]}`);if(el)el.classList.toggle('pressed',on)}
function dpadAt(x,y){const r=$('#dpad').getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=(x-cx)/(r.width/2),dy=(y-cy)/(r.height/2),mag=Math.hypot(dx,dy);if(mag<.13)return[];const out=[];if(dy<-.25)out.push('ArrowUp');if(dy>.25)out.push('ArrowDown');if(dx<-.25)out.push('ArrowLeft');if(dx>.25)out.push('ArrowRight');if(!out.length){if(Math.abs(dx)>Math.abs(dy))out.push(dx>0?'ArrowRight':'ArrowLeft');else out.push(dy>0?'ArrowDown':'ArrowUp')}return out}
function bindDpad(){const z=$('#dpadZone');z.addEventListener('pointerdown',e=>{dpadPointer=e.pointerId;z.setPointerCapture?.(e.pointerId);setDirs(dpadAt(e.clientX,e.clientY));e.preventDefault()});z.addEventListener('pointermove',e=>{if(e.pointerId===dpadPointer)setDirs(dpadAt(e.clientX,e.clientY))});['pointerup','pointercancel','lostpointercapture'].forEach(t=>z.addEventListener(t,e=>{if(dpadPointer===null||e.pointerId===dpadPointer){setDirs([]);dpadPointer=null}}))}
function pressButton(el,down){const key=el.dataset.key;if(!key)return;el.classList.toggle('pressed',down);if(down){haptic();emitKey(key,true);if(turboOn&&(key==='z'||key==='x')){clearInterval(turboTimers[key]);turboTimers[key]=setInterval(()=>{emitKey(key,false);setTimeout(()=>emitKey(key,true),24)},90)}}else{clearInterval(turboTimers[key]);delete turboTimers[key];emitKey(key,false)}}
function bindButtons(){$$('.actionZone [data-key]').forEach(el=>{el.addEventListener('pointerdown',e=>{el.setPointerCapture?.(e.pointerId);pressButton(el,true);e.preventDefault()});['pointerup','pointercancel','lostpointercapture'].forEach(t=>el.addEventListener(t,()=>pressButton(el,false)))})}
function releaseAll(){setDirs([]);$$('.actionZone [data-key]').forEach(el=>pressButton(el,false))}
function setWidth(){const w=widths[widthIndex];document.documentElement.style.setProperty('--stageScale',w/100);$('#widthLabel').textContent=w+'%';saveSettings()}
function setSound(){soundOn=!soundOn;$('#soundIcon').textContent=soundOn?'🔊':'🔇';try{window.EJS_emulator?.setVolume?.(soundOn?1:0)}catch(e){}saveSettings()}
function setTurbo(){turboOn=!turboOn;$('#turboLabel').textContent='連發 '+(turboOn?'ON':'OFF');saveSettings()}
function setVoice(v){voiceOn=v;$('#voiceIcon').textContent=v?'🎙':'🔇';$('#voiceLabel').textContent='語音 '+(v?'ON':'OFF');localStream?.getAudioTracks().forEach(t=>t.enabled=v);saveSettings()}
function applyControls(){const vals={leftX:$('#leftX').value,leftY:$('#leftY').value,rightX:$('#rightX').value,rightY:$('#rightY').value,scale:$('#controlScale').value};document.documentElement.style.setProperty('--leftX',vals.leftX+'vw');document.documentElement.style.setProperty('--leftY',vals.leftY+'vh');document.documentElement.style.setProperty('--rightX',vals.rightX+'vw');document.documentElement.style.setProperty('--rightY',vals.rightY+'vh');document.documentElement.style.setProperty('--controlScale',vals.scale/100);$('#leftXOut').textContent=vals.leftX;$('#leftYOut').textContent=vals.leftY;$('#rightXOut').textContent=vals.rightX;$('#rightYOut').textContent=vals.rightY;$('#scaleOut').textContent=vals.scale+'%';saveSettings()}
function resetControls(){$('#leftX').value=0;$('#leftY').value=0;$('#rightX').value=0;$('#rightY').value=0;$('#controlScale').value=100;applyControls()}
function openModal(id){$(id).classList.add('show')}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('show'))}
function genCode(){return String(Math.floor(1000+Math.random()*9000))}
function setStatus(s,ok=false){$('#roomStatus').textContent='● '+s;$('#roomStatus').classList.toggle('connected',ok)}
function setupPeerEvents(){peer.on('connection',c=>{if(conn?.open){c.close();return}conn=c;bindConn(c)});peer.on('call',call=>{getMic().then(stream=>{mediaCall=call;call.answer(stream);call.on('stream',rs=>$('#remoteAudio').srcObject=rs)})});peer.on('error',()=>setStatus('連線失敗，請重試'))}
function bindConn(c){c.on('open',()=>{setStatus('已連線',true);if(voiceOn)startVoice()});c.on('data',d=>{if(d?.t==='key')emitKey(isHost?remoteMap(d.key):d.key,d.down,true)});c.on('close',()=>setStatus('對方已離線'))}
async function createRoom(){roomCode=genCode();isHost=true;$('#roomCode').textContent=roomCode;setStatus('建立房間中…');peer?.destroy();peer=new Peer('meme-'+roomCode);setupPeerEvents();peer.on('open',()=>setStatus('等待朋友加入 '+roomCode))}
async function joinRoom(){const code=$('#joinCode').value.replace(/\D/g,'').slice(0,4);if(code.length!==4){setStatus('請輸入 4 碼');return}roomCode=code;isHost=false;setStatus('連線中…');peer?.destroy();peer=new Peer();setupPeerEvents();peer.on('open',()=>{conn=peer.connect('meme-'+code,{reliable:true});bindConn(conn)})}
async function getMic(){if(localStream)return localStream;localStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});localStream.getAudioTracks().forEach(t=>t.enabled=voiceOn);return localStream}
async function startVoice(){if(!voiceOn||!peer||!roomCode)return;try{const stream=await getMic();if(!isHost){mediaCall=peer.call('meme-'+roomCode,stream);mediaCall.on('stream',rs=>$('#remoteAudio').srcObject=rs)}}catch(e){setStatus('已連線・麥克風未授權',true)}}
function initInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}else showInstallHelp()});if(!window.matchMedia('(display-mode: standalone)').matches&&!navigator.standalone){setTimeout(()=>$('#installBtn').classList.remove('hidden'),700)}}
function showInstallHelp(){const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installInstructions').innerHTML=ios?'<b>iPhone / iPad</b><br>使用 Safari 開啟 → 點「分享」 →「加入主畫面」→「加入」。':'<b>Android / Chrome</b><br>點瀏覽器選單 →「安裝應用程式」或「加入主畫面」。';openModal('#installModal')}
function bindUI(){$('#quickToggle').onclick=()=>$('#quickMenu').classList.toggle('open');$('#fullscreenLauncherBtn').onclick=toggleFullscreen;$('#openRoomBtn').onclick=()=>openModal('#roomModal');$$('#quickMenu [data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='sound')setSound();if(a==='width'){widthIndex=(widthIndex+1)%widths.length;setWidth()}if(a==='voice')setVoice(!voiceOn);if(a==='controls')openModal('#controlsModal');if(a==='turbo')setTurbo();if(a==='fullscreen')toggleFullscreen();if(a==='room')openModal('#roomModal');if(a==='home')goHome()});$$('[data-close]').forEach(b=>b.onclick=closeModals);$$('.modal').forEach(m=>m.addEventListener('pointerdown',e=>{if(e.target===m)closeModals()}));$$('[data-roomtab]').forEach(b=>b.onclick=()=>{$$('[data-roomtab]').forEach(x=>x.classList.toggle('active',x===b));$('#hostPane').classList.toggle('show',b.dataset.roomtab==='host');$('#joinPane').classList.toggle('show',b.dataset.roomtab==='join')});$('#createRoomBtn').onclick=createRoom;$('#joinRoomBtn').onclick=joinRoom;$('#joinCode').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,4));$('#copyCode').onclick=()=>roomCode&&navigator.clipboard?.writeText(roomCode);['#leftX','#leftY','#rightX','#rightY','#controlScale'].forEach(id=>$(id).addEventListener('input',applyControls));$('#resetControls').onclick=resetControls;document.addEventListener('visibilitychange',()=>{if(document.hidden)releaseAll()})}
function restore(){soundOn=saved.soundOn??true;voiceOn=saved.voiceOn??true;turboOn=saved.turboOn??false;widthIndex=saved.widthIndex??0;$('#leftX').value=saved.leftX??0;$('#leftY').value=saved.leftY??0;$('#rightX').value=saved.rightX??0;$('#rightY').value=saved.rightY??0;$('#controlScale').value=saved.scale??100;$('#soundIcon').textContent=soundOn?'🔊':'🔇';$('#voiceIcon').textContent=voiceOn?'🎙':'🔇';$('#voiceLabel').textContent='語音 '+(voiceOn?'ON':'OFF');$('#turboLabel').textContent='連發 '+(turboOn?'ON':'OFF');setWidth();applyControls()}
renderGames();bindDpad();bindButtons();bindUI();restore();initInstall();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});