const $=s=>document.querySelector(s);const games=[{id:'knightsj',title:'圓桌武士',sub:'Knights of the Round · Japan',ready:true},{id:'slot2',title:'遊戲 02',sub:'等待你提供 ROM',ready:false},{id:'slot3',title:'遊戲 03',sub:'等待你提供 ROM',ready:false}];let deferredPrompt=null,peer=null,conn=null,stream=null;
function render(){ $('#games').innerHTML=games.map((g,i)=>`<button class="game ${g.ready?'':'disabled'}" ${g.ready?`data-id="${g.id}"`:''}><span class="n">0${i+1}</span><strong>${g.title}</strong><small>${g.sub}</small></button>`).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>openGame(b.dataset.id));}
function openGame(id,net=''){location.href=`player.html?game=${encodeURIComponent(id)}${net?`&${net}`:''}`}
function full(){document.documentElement.requestFullscreen?.().catch(()=>{});screen.orientation?.lock?.('landscape').catch?.(()=>{})}
function code(){return String(Math.floor(1000+Math.random()*9000))}
async function mic(){try{return await navigator.mediaDevices.getUserMedia({audio:true,video:false})}catch{return null}}
async function host(){const c=code();$('#roomCode').textContent=c;$('#netStatus').textContent='建立房間中…';stream=await mic();peer=new Peer(`arcade-${c}-host`);peer.on('open',()=>{$('#netStatus').textContent='房間已建立，進入遊戲後等待朋友';setTimeout(()=>openGame('knightsj',`role=host&room=${c}&voice=${stream?'1':'0'}`),350)});peer.on('error',()=>$('#netStatus').textContent='房號衝突，請再建立一次')}
function join(){const c=$('#joinInput').value.replace(/\D/g,'').slice(0,4);if(c.length!==4){$('#netStatus').textContent='請輸入 4 碼';return}openGame('knightsj',`role=guest&room=${c}&voice=1`)}
function pwa(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBar').classList.remove('hidden')});const ios=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=window.matchMedia('(display-mode: standalone)').matches||navigator.standalone;if(!standalone&&!localStorage.getItem('pwaDismiss')){if(ios){$('#installText').textContent='iPhone/iPad：加入主畫面';$('#installBar').classList.remove('hidden')}else setTimeout(()=>$('#installBar').classList.remove('hidden'),1000)}$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBar').classList.add('hidden')}else if(ios)alert('Safari：點「分享」→「加入主畫面」。');else alert('請使用 Chrome / Edge 的「安裝應用程式」功能。')};$('#installDismiss').onclick=()=>{$('#installBar').classList.add('hidden');localStorage.setItem('pwaDismiss','1')}}
render();$('#homeFull').onclick=full;$('#multiBtn').onclick=()=>$('#multiModal').classList.remove('hidden');$('#multiClose').onclick=()=>$('#multiModal').classList.add('hidden');$('#hostBtn').onclick=host;$('#joinBtn').onclick=join;pwa();
