const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const widths=[100,95,90,85,80,75,70,65,60];const S={joy:null,cx:0,cy:0,inner:18,outer:72,currentDirs:new Set(),dirTimers:new Map(),pressed:new Map(),buttonTimes:{0:0,8:0},turbo:{0:false,8:false},turboTimers:new Map(),hz:12,role:window.ARCADE_NET?.role||'',room:window.ARCADE_NET?.room||'',peer:null,conn:null,voice:true,mic:null,remoteAudio:null};
const defaults={screen:0,fill:true,leftSize:100,leftX:0,leftY:0,rightSize:100,rightX:0,rightY:0};let cfg={...defaults,...JSON.parse(localStorage.getItem('arcadeControlsV11')||'{}')};
function localSim(player,input,down){try{if(typeof window.simulate_input==='function'){window.simulate_input(player,input,down?1:0);return true}}catch{}const map={0:'x',1:'s',2:'v',3:'Enter',4:'ArrowUp',5:'ArrowDown',6:'ArrowLeft',7:'ArrowRight',8:'z',9:'a'};if(player!==0)return false;const k=map[input];if(!k)return false;const ev=new KeyboardEvent(down?'keydown':'keyup',{key:k,code:k,bubbles:true,cancelable:true});window.dispatchEvent(ev);document.dispatchEvent(ev);return true}
function send(input,down){if(S.role==='guest'){if(S.conn?.open)S.conn.send({t:'i',input,down});return}localSim(0,input,down)}
function rawPress(i){if(S.pressed.get(i))return;S.pressed.set(i,true);send(i,true)}function rawRelease(i){if(!S.pressed.get(i))return;S.pressed.delete(i);send(i,false)}
function press(i){const now=performance.now();if(i===0||i===8){const other=i===0?8:0;if(now-(S.buttonTimes[other]||0)<=30){rawPress(0);rawPress(8)}S.buttonTimes[i]=now}if(S.turbo[i]){if(S.turboTimers.has(i))return;rawPress(i);let on=true;const id=setInterval(()=>{on=!on;on?rawPress(i):rawRelease(i)},Math.max(32,500/S.hz));S.turboTimers.set(i,id)}else rawPress(i)}
function release(i){if(S.turboTimers.has(i)){clearInterval(S.turboTimers.get(i));S.turboTimers.delete(i)}rawRelease(i)}
function setDirs(next){[4,5,6,7].forEach(i=>{if(next.has(i)){const t=S.dirTimers.get(i);if(t){clearTimeout(t);S.dirTimers.delete(i)}if(!S.currentDirs.has(i)){S.currentDirs.add(i);press(i)}}else if(S.currentDirs.has(i)&&!S.dirTimers.has(i)){S.dirTimers.set(i,setTimeout(()=>{S.dirTimers.delete(i);if(!next.has(i)){S.currentDirs.delete(i);release(i)}},34))}})}
function direction(dx,dy){const m=Math.hypot(dx,dy);if(m<S.inner){setDirs(new Set());return}const a=(Math.atan2(dy,dx)*180/Math.PI+360)%360;let arr;if(a>=337.5||a<22.5)arr=[7];else if(a<67.5)arr=[7,5];else if(a<112.5)arr=[5];else if(a<157.5)arr=[5,6];else if(a<202.5)arr=[6];else if(a<247.5)arr=[6,4];else if(a<292.5)arr=[4];else arr=[4,7];setDirs(new Set(arr))}
function joystick(){const z=$('#leftZone'),j=$('#joy'),knob=j.querySelector('i');z.addEventListener('pointerdown',e=>{if(S.joy!==null)return;S.joy=e.pointerId;S.cx=e.clientX;S.cy=e.clientY;z.setPointerCapture(e.pointerId);j.style.left=e.clientX+'px';j.style.top=e.clientY+'px';j.classList.remove('hidden');knob.style.transform='translate(-50%,-50%)'});z.addEventListener('pointermove',e=>{if(e.pointerId!==S.joy)return;let dx=e.clientX-S.cx,dy=e.clientY-S.cy,m=Math.hypot(dx,dy);if(m>S.outer){dx=dx/m*S.outer;dy=dy/m*S.outer}knob.style.transform=`translate(calc(-50% + ${dx}px),calc(-50% + ${dy}px))`;direction(dx,dy)});const end=e=>{if(e.pointerId!==S.joy)return;S.joy=null;j.classList.add('hidden');setDirs(new Set())};z.addEventListener('pointerup',end);z.addEventListener('pointercancel',end)}
function buttons(){$$('[data-input],[data-combo]').forEach(el=>{const inputs=el.dataset.combo?el.dataset.combo.split(',').map(Number):[Number(el.dataset.input)];const ids=new Set();el.addEventListener('pointerdown',e=>{e.preventDefault();ids.add(e.pointerId);el.setPointerCapture?.(e.pointerId);el.classList.add('pressed');inputs.forEach(press)});const up=e=>{if(!ids.has(e.pointerId))return;ids.delete(e.pointerId);if(!ids.size)el.classList.remove('pressed');inputs.forEach(release)};el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)})}
function save(){localStorage.setItem('arcadeControlsV11',JSON.stringify(cfg))}function apply(){document.documentElement.style.setProperty('--screenW',cfg.fill?'100%':widths[cfg.screen]+'%');document.documentElement.style.setProperty('--leftScale',cfg.leftSize/100);document.documentElement.style.setProperty('--leftX',cfg.leftX+'vw');document.documentElement.style.setProperty('--leftY',cfg.leftY+'vh');document.documentElement.style.setProperty('--rightScale',cfg.rightSize/100);document.documentElement.style.setProperty('--rightX',cfg.rightX+'vw');document.documentElement.style.setProperty('--rightY',cfg.rightY+'vh');$('#screenWidth').value=cfg.screen;$('#screenOut').value=(cfg.fill?100:widths[cfg.screen])+'%';['leftSize','leftX','leftY','rightSize','rightX','rightY'].forEach(k=>{$('#'+k).value=cfg[k];$('#'+k+'Out').value=(k.includes('Size')?cfg[k]+'%':cfg[k])});$('#fillBtn').classList.toggle('on',cfg.fill);$('#fillBtn').textContent=cfg.fill?'開':'關'}
function menu(){const m=$('#menu');$('#menuBtn').onclick=()=>m.classList.toggle('hidden');$('#menuClose').onclick=()=>m.classList.add('hidden');$('#backHome').onclick=()=>location.href='./';$('#fillBtn').onclick=()=>{cfg.fill=!cfg.fill;apply();save()};$('#screenWidth').oninput=e=>{cfg.screen=+e.target.value;cfg.fill=false;apply();save()};['leftSize','leftX','leftY','rightSize','rightX','rightY'].forEach(k=>$('#'+k).oninput=e=>{cfg[k]=+e.target.value;apply();save()});$('#resetControls').onclick=()=>{cfg={...defaults};apply();save()};$('#soundBtn').onclick=()=>{const on=$('#soundBtn').classList.toggle('on');$('#soundBtn').textContent=on?'開':'關';try{window.EJS_emulator?.setVolume?.(on?1:0)}catch{}document.querySelectorAll('audio,video').forEach(x=>x.muted=!on)};function turbo(btn,input){$(btn).onclick=()=>{S.turbo[input]=!S.turbo[input];$(btn).classList.toggle('on',S.turbo[input]);$(btn).textContent=S.turbo[input]?'開':'關'}}turbo('#turboA',0);turbo('#turboB',8);$('#turboHz').oninput=e=>{S.hz=+e.target.value;$('#turboOut').value=S.hz+'Hz'};$('#voiceBtn').onclick=()=>{S.voice=!S.voice;$('#voiceBtn').classList.toggle('on',S.voice);$('#voiceBtn').textContent=S.voice?'開':'關';if(S.mic)S.mic.getAudioTracks().forEach(t=>t.enabled=S.voice)};apply()}
async function getMic(){if(!S.voice)return null;try{return await navigator.mediaDevices.getUserMedia({audio:true})}catch{return null}}
function attachAudio(stream){if(!S.remoteAudio){S.remoteAudio=new Audio();S.remoteAudio.autoplay=true}S.remoteAudio.srcObject=stream}
async function hostNet(){if(!S.room)return;$('#netLine').textContent=`房間 ${S.room} · 等待玩家 2`;S.mic=await getMic();S.peer=new Peer(`arcade-${S.room}-host`);S.peer.on('connection',c=>{S.conn=c;$('#netLine').textContent=`房間 ${S.room} · 玩家 2 已連線`;c.on('data',d=>{if(d?.t==='i')localSim(1,+d.input,!!d.down)});setTimeout(()=>{const canvas=document.querySelector('#game canvas');if(canvas?.captureStream){const vs=canvas.captureStream(60);const combo=new MediaStream([...vs.getVideoTracks(),...(S.mic?.getAudioTracks()||[])]);S.peer.call(c.peer,combo)}},800)});S.peer.on('call',call=>{call.answer(S.mic||undefined);call.on('stream',attachAudio)})}
async function guestNet(){if(!S.room)return;$('#netLine').textContent=`房間 ${S.room} · 連接中`;S.mic=await getMic();S.peer=new Peer();S.peer.on('open',()=>{S.conn=S.peer.connect(`arcade-${S.room}-host`);S.conn.on('open',()=>{$('#netLine').textContent=`房間 ${S.room} · 已連線`;$('#loadingText').textContent='等待主機畫面…';if(S.mic){const c=S.peer.call(`arcade-${S.room}-host`,S.mic);c.on('stream',s=>{const video=$('#remoteVideo');video.srcObject=s;video.play().catch(()=>{});$('#loading').classList.add('hidden')})}})});S.peer.on('call',call=>{call.answer(S.mic||undefined);call.on('stream',s=>{const video=$('#remoteVideo');video.srcObject=s;video.play().catch(()=>{});$('#loading').classList.add('hidden')})});S.peer.on('error',()=>{$('#netLine').textContent='連線失敗';$('#loadingText').textContent='找不到房間或主機已離線'})}
function cleanup(){[...S.pressed.keys()].forEach(release);setDirs(new Set())}window.addEventListener('blur',cleanup);document.addEventListener('visibilitychange',()=>{if(document.hidden)cleanup()});document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('DOMContentLoaded',()=>{joystick();buttons();menu();setTimeout(()=>screen.orientation?.lock?.('landscape').catch?.(()=>{}),250);if(S.role==='host')setTimeout(hostNet,1400);else if(S.role==='guest')guestNet();else $('#netLine').textContent='單機模式'});
